/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Modifier_mecaniciens.java
 *
 * Created on 6 avr. 2014, 01:55:11
 */
package pfe;

import java.awt.print.PrinterException;
import java.sql.*;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
public class Modifier_mecaniciens extends javax.swing.JFrame {

    Connexion cnx = new Connexion();
    Statement stmt;
    public Modifier_mecaniciens() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        text_nom = new javax.swing.JTextField();
        num_cin = new javax.swing.JTextField();
        text_prenom = new javax.swing.JTextField();
        text_grade = new javax.swing.JTextField();
        text_experience = new javax.swing.JTextField();
        date_debut = new javax.swing.JTextField();
        date_fin = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_mecanicien = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        date_premier = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        nouv_contrat = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        salaire = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        mat_mec = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pfe.PFEApp.class).getContext().getResourceMap(Modifier_mecaniciens.class);
        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setFont(resourceMap.getFont("jLabel7.font")); // NOI18N
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel10.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setFont(resourceMap.getFont("jLabel11.font")); // NOI18N
        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        text_nom.setName("text_nom"); // NOI18N

        num_cin.setName("num_cin"); // NOI18N

        text_prenom.setName("text_prenom"); // NOI18N

        text_grade.setName("text_grade"); // NOI18N

        text_experience.setName("text_experience"); // NOI18N

        date_debut.setName("date_debut"); // NOI18N

        date_fin.setName("date_fin"); // NOI18N

        jButton4.setIcon(resourceMap.getIcon("jButton4.icon")); // NOI18N
        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(resourceMap.getFont("jLabel8.font")); // NOI18N
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(resourceMap.getIcon("jButton2.icon")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setIcon(resourceMap.getIcon("jButton5.icon")); // NOI18N
        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setIcon(resourceMap.getIcon("jButton3.icon")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        table_mecanicien.setAutoCreateRowSorter(true);
        table_mecanicien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricule", "CIN", "Nom", "Prenom", "Grade", "Expérience", "Date debut de contrat", "Date fin de contrat", "date premier contrat", "Salaire"
            }
        ));
        table_mecanicien.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table_mecanicien.setName("table_mecanicien"); // NOI18N
        table_mecanicien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_mecanicienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_mecanicien);
        table_mecanicien.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("table_mecanicien.columnModel.title9")); // NOI18N
        table_mecanicien.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("table_mecanicien.columnModel.title0")); // NOI18N
        table_mecanicien.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("table_mecanicien.columnModel.title1")); // NOI18N
        table_mecanicien.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("table_mecanicien.columnModel.title2")); // NOI18N
        table_mecanicien.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("table_mecanicien.columnModel.title4")); // NOI18N
        table_mecanicien.getColumnModel().getColumn(5).setHeaderValue(resourceMap.getString("table_mecanicien.columnModel.title5")); // NOI18N
        table_mecanicien.getColumnModel().getColumn(6).setHeaderValue(resourceMap.getString("table_mecanicien.columnModel.title6")); // NOI18N
        table_mecanicien.getColumnModel().getColumn(7).setHeaderValue(resourceMap.getString("table_mecanicien.columnModel.title7")); // NOI18N
        table_mecanicien.getColumnModel().getColumn(8).setHeaderValue(resourceMap.getString("table_mecanicien.columnModel.title3")); // NOI18N
        table_mecanicien.getColumnModel().getColumn(9).setHeaderValue(resourceMap.getString("table_mecanicien.columnModel.title8")); // NOI18N

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        date_premier.setName("date_premier"); // NOI18N

        jButton6.setText(resourceMap.getString("jButton6.text")); // NOI18N
        jButton6.setName("jButton6"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText(resourceMap.getString("jButton7.text")); // NOI18N
        jButton7.setName("jButton7"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        nouv_contrat.setText(resourceMap.getString("nouv_contrat.text")); // NOI18N
        nouv_contrat.setName("nouv_contrat"); // NOI18N
        nouv_contrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouv_contratActionPerformed(evt);
            }
        });

        jLabel9.setFont(resourceMap.getFont("jLabel9.font")); // NOI18N
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        salaire.setName("salaire"); // NOI18N

        jLabel12.setFont(resourceMap.getFont("jLabel12.font")); // NOI18N
        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        mat_mec.setText(resourceMap.getString("mat_mec.text")); // NOI18N
        mat_mec.setName("mat_mec"); // NOI18N

        jButton8.setText(resourceMap.getString("jButton8.text")); // NOI18N
        jButton8.setName("jButton8"); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nouv_contrat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addComponent(jButton5))
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_grade, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(date_fin, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(date_debut, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(text_experience, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                .addComponent(date_premier, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(salaire, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(num_cin, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text_prenom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(text_nom, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mat_mec))
                                .addGap(27, 27, 27)
                                .addComponent(jButton4)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mat_mec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton4))
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(num_cin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(text_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(text_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(text_grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(text_experience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(date_debut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(date_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(date_premier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(salaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(nouv_contrat))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton6)
                                .addComponent(jButton8)))
                        .addGap(13, 13, 13))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
    Acceil acc = new Acceil();
    acc.setVisible(true);
    setVisible(false);
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try{
    stmt=cnx.obtenircon().createStatement();
    String stringmat=mat_mec.getText();
    
    int mat=Integer.parseInt(stringmat);
    System.out.println(mat);
    ResultSet result=stmt.executeQuery("select * from mecanicien as MC where MC.num_mecanicien ="+mat);
    while(result.next()){
        num_cin.setText(result.getString("cin"));
        text_nom.setText(result.getString("nom_mecanicien"));
        text_prenom.setText(result.getString("prenom_mecanicien"));
        text_grade.setText(result.getString("grade"));
        text_experience.setText(result.getString("experience"));
        date_debut.setText(result.getString("date_debut_contrat"));
        date_fin.setText(result.getString("date_fin_contrat"));
        date_premier.setText(result.getString("date_premier_contrat"));
        salaire.setText(result.getString("salaire"));
    }
    }catch(SQLException exp){
        JOptionPane.showMessageDialog(null, "erreur");
    }
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int cin = Integer.parseInt(num_cin.getText());
int exp = Integer.parseInt(text_experience.getText());
    try{
    
    stmt=cnx.obtenircon().createStatement();
    stmt.execute("update mecanicien set cin='"+cin+"', nom_mecanicien='"+text_nom.getText()+"', prenom_mecanicien='"+text_prenom.getText()+"', date_premier_contrat='"+date_premier.getText()+"', date_debut_contrat='"+date_debut.getText()+"', date_fin_contrat='"+date_fin.getText()+"', grade='"+text_grade.getText()+"', experience='"+exp+"', salaire='"+Double.parseDouble(salaire.getText())+"' where cin='"+cin+"'");
    JOptionPane.showMessageDialog(null, "modifié");
    }catch(SQLException e){
    JOptionPane.showMessageDialog(null, e);
}
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
num_cin.setText("");text_nom.setText("");text_prenom.setText("");
text_grade.setText("");text_experience.setText("");
date_debut.setText("");date_fin.setText("");mat_mec.setText("");
date_premier.setText("");salaire.setText("");
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    int cin=Integer.parseInt(num_cin.getText());
    int conf=JOptionPane.showConfirmDialog(null, "voulez vous vraiament supprimer?");
    if(conf == 0){
    try{
    stmt=cnx.obtenircon().createStatement();
    stmt.execute("delete from mecanicien where cin ="+cin);
    JOptionPane.showMessageDialog(null,"bien effacé");
    num_cin.setText("");text_nom.setText("");text_prenom.setText("");
text_grade.setText("");text_experience.setText("");
date_debut.setText("");date_fin.setText("");
date_premier.setText("");salaire.setText("");
    }
    catch(SQLException e){
     JOptionPane.showMessageDialog(null,"bien effacé");   
    }
}//GEN-LAST:event_jButton5ActionPerformed
    else{JOptionPane.showMessageDialog(null,"annulé");}
}
private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
DefaultTableModel table=(DefaultTableModel) table_mecanicien.getModel();
    
    try{
   
    stmt=   (Statement) cnx.obtenircon().createStatement();
    ResultSet rslt=stmt.executeQuery("select * from mecanicien");
    while(rslt.next()){
         
    table.addRow(new Object[] {rslt.getObject("num_mecanicien"),rslt.getObject("cin"),rslt.getObject("nom_mecanicien"),rslt.getObject("prenom_mecanicien"),rslt.getObject("grade"),rslt.getObject("experience"),rslt.getObject("date_premier_contrat"),rslt.getObject("date_debut_contrat"),rslt.getObject("date_fin_contrat"),rslt.getObject("salaire")});
        //i++;
    }
    
    
}                                        
catch(SQLException exp){
    JOptionPane.showMessageDialog(null,"erreur d'affichage");
}
}//GEN-LAST:event_jButton6ActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
MessageFormat header = new MessageFormat("Sotacib liste des véhicules");
MessageFormat footer = new MessageFormat("Page{0,Number, Integer}");
try{
    table_mecanicien.print(JTable.PrintMode.NORMAL, header, footer);
}catch(PrinterException e){
    System.err.format("cannot print", e.getMessage());
}
}//GEN-LAST:event_jButton7ActionPerformed

private void nouv_contratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouv_contratActionPerformed
nouv_contrat_mecanicien ncm = new nouv_contrat_mecanicien();
ncm.setVisible(true);

}//GEN-LAST:event_nouv_contratActionPerformed

private void table_mecanicienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_mecanicienMouseClicked
try{
    stmt=cnx.obtenircon().createStatement();
    
    int row=table_mecanicien.getSelectedRow();
    String table = (table_mecanicien.getModel().getValueAt(row,0).toString());
    ResultSet rs =stmt.executeQuery("select * from mecanicien where num_mecanicien="+table);
    if(rs.next()){
        String add13=rs.getString("num_mecanicien");
        mat_mec.setText(add13);
        String add1=rs.getString("cin");
        num_cin.setText(add1);
        String add2=rs.getString("nom_mecanicien");
        text_nom.setText(add2);
        String add3=rs.getString("prenom_mecanicien");
        text_prenom.setText(add3);
        String add4=rs.getString("date_premier_contrat");
        date_premier.setText(add4);
        String add5=rs.getString("date_debut_contrat");
        date_debut.setText(add5);
        String add6=rs.getString("date_fin_contrat");
        date_fin.setText(add6);
        String add7=rs.getString("experience");
        text_experience.setText(add7);
        String add11=rs.getString("grade");
        text_grade.setText(add11);
        String add12=rs.getString("salaire");
        salaire.setText(add12);
    }
}catch(Exception e){
    
}
}//GEN-LAST:event_table_mecanicienMouseClicked

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
DefaultTableModel model=(DefaultTableModel) table_mecanicien.getModel();
model.setValueAt(mat_mec.getText(), table_mecanicien.getSelectedRow(),0);
model.setValueAt(num_cin.getText(), table_mecanicien.getSelectedRow(),1);
model.setValueAt(text_nom.getText(), table_mecanicien.getSelectedRow(),2);
model.setValueAt(text_prenom.getText(), table_mecanicien.getSelectedRow(),3);
model.setValueAt(text_grade.getText(), table_mecanicien.getSelectedRow(),4);
model.setValueAt(text_experience.getText(), table_mecanicien.getSelectedRow(),5);
model.setValueAt(date_debut.getText(), table_mecanicien.getSelectedRow(),6);
model.setValueAt(date_fin.getText(), table_mecanicien.getSelectedRow(),7);
model.setValueAt(date_premier.getText(), table_mecanicien.getSelectedRow(),8);
model.setValueAt(salaire.getText(), table_mecanicien.getSelectedRow(),9);
}//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modifier_mecaniciens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modifier_mecaniciens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modifier_mecaniciens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modifier_mecaniciens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Modifier_mecaniciens().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date_debut;
    private javax.swing.JTextField date_fin;
    private javax.swing.JTextField date_premier;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mat_mec;
    private javax.swing.JButton nouv_contrat;
    private javax.swing.JTextField num_cin;
    private javax.swing.JTextField salaire;
    private javax.swing.JTable table_mecanicien;
    private javax.swing.JTextField text_experience;
    private javax.swing.JTextField text_grade;
    private javax.swing.JTextField text_nom;
    private javax.swing.JTextField text_prenom;
    // End of variables declaration//GEN-END:variables
}
