/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Supprimer_chauffeurs.java
 *
 * Created on 4 avr. 2014, 00:20:27
 */
package pfe;
import java.awt.print.PrinterException;
import java.sql.*;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
public class Supprimer_chauffeurs extends javax.swing.JFrame {

    /** Creates new form Supprimer_chauffeurs */
    Connexion cnx = new Connexion();
    Statement stmt;
    public Supprimer_chauffeurs() {
        setTitle("Supprimer chauffeurs");
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cin = new javax.swing.JTextField();
        text_nom = new javax.swing.JTextField();
        text_prenom = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        text_type_permis = new javax.swing.JTextField();
        text_service = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablechauffeur = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        text_date_premier_contrat = new javax.swing.JTextField();
        text_date_fin_contrat = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        text_date_debut_contrat = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        text_grade = new javax.swing.JTextField();
        text_experience = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        text_direction = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        nbr_mission = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        salaire = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        mat = new javax.swing.JTextField();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pfe.PFEApp.class).getContext().getResourceMap(Supprimer_chauffeurs.class);
        popupMenu1.setLabel(resourceMap.getString("popupMenu1.label")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel7.setFont(resourceMap.getFont("jLabel7.font")); // NOI18N
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setFont(resourceMap.getFont("jLabel8.font")); // NOI18N
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        cin.setText(resourceMap.getString("cin.text")); // NOI18N
        cin.setName("cin"); // NOI18N

        text_nom.setText(resourceMap.getString("text_nom.text")); // NOI18N
        text_nom.setName("text_nom"); // NOI18N

        text_prenom.setText(resourceMap.getString("text_prenom.text")); // NOI18N
        text_prenom.setName("text_prenom"); // NOI18N

        jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(resourceMap.getIcon("jButton2.icon")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(resourceMap.getIcon("jButton3.icon")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        text_type_permis.setName("text_type_permis"); // NOI18N

        text_service.setName("text_service"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tablechauffeur.setAutoCreateRowSorter(true);
        tablechauffeur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "matricule", "CIN", "Nom", "Prenom", "Type de permis", "Expérience", "Date premier contrat", "Date debut de contrat", "Date fin de contrat", "Service", "grade", "Direction", "nbr mission", "salaire"
            }
        ));
        tablechauffeur.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tablechauffeur.setName("tablechauffeur"); // NOI18N
        tablechauffeur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablechauffeurMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablechauffeur);
        tablechauffeur.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("tablechauffeur.columnModel.title13")); // NOI18N
        tablechauffeur.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("tablechauffeur.columnModel.title0")); // NOI18N
        tablechauffeur.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("tablechauffeur.columnModel.title1")); // NOI18N
        tablechauffeur.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("tablechauffeur.columnModel.title2")); // NOI18N
        tablechauffeur.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("tablechauffeur.columnModel.title3")); // NOI18N
        tablechauffeur.getColumnModel().getColumn(5).setHeaderValue(resourceMap.getString("jTable1.columnModel.title5")); // NOI18N
        tablechauffeur.getColumnModel().getColumn(6).setResizable(false);
        tablechauffeur.getColumnModel().getColumn(6).setHeaderValue(resourceMap.getString("jTable1.columnModel.title8")); // NOI18N
        tablechauffeur.getColumnModel().getColumn(7).setHeaderValue(resourceMap.getString("tablechauffeur.columnModel.title6")); // NOI18N
        tablechauffeur.getColumnModel().getColumn(8).setHeaderValue(resourceMap.getString("tablechauffeur.columnModel.title7")); // NOI18N
        tablechauffeur.getColumnModel().getColumn(9).setHeaderValue(resourceMap.getString("jTable1.columnModel.title9")); // NOI18N
        tablechauffeur.getColumnModel().getColumn(10).setHeaderValue(resourceMap.getString("tablechauffeur.columnModel.title10")); // NOI18N
        tablechauffeur.getColumnModel().getColumn(11).setHeaderValue(resourceMap.getString("jTable1.columnModel.title10")); // NOI18N
        tablechauffeur.getColumnModel().getColumn(12).setHeaderValue(resourceMap.getString("tablechauffeur.columnModel.title11")); // NOI18N
        tablechauffeur.getColumnModel().getColumn(13).setHeaderValue(resourceMap.getString("tablechauffeur.columnModel.title12")); // NOI18N

        jLabel9.setFont(resourceMap.getFont("jLabel9.font")); // NOI18N
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jButton4.setIcon(resourceMap.getIcon("jButton4.icon")); // NOI18N
        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel10.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setFont(resourceMap.getFont("jLabel11.font")); // NOI18N
        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        jButton5.setIcon(resourceMap.getIcon("jButton5.icon")); // NOI18N
        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        text_date_premier_contrat.setName("text_date_premier_contrat"); // NOI18N

        text_date_fin_contrat.setName("text_date_fin_contrat"); // NOI18N

        jLabel12.setFont(resourceMap.getFont("jLabel12.font")); // NOI18N
        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        text_date_debut_contrat.setName("text_date_debut_contrat"); // NOI18N

        jLabel13.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        text_grade.setName("text_grade"); // NOI18N

        text_experience.setName("text_experience"); // NOI18N

        jButton6.setText(resourceMap.getString("jButton6.text")); // NOI18N
        jButton6.setName("jButton6"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText(resourceMap.getString("jButton7.text")); // NOI18N
        jButton7.setName("jButton7"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText(resourceMap.getString("jButton8.text")); // NOI18N
        jButton8.setName("jButton8"); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel14.setFont(resourceMap.getFont("jLabel14.font")); // NOI18N
        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        text_direction.setName("text_direction"); // NOI18N

        jLabel15.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        nbr_mission.setName("nbr_mission"); // NOI18N

        jLabel6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        salaire.setName("salaire"); // NOI18N

        jLabel16.setFont(resourceMap.getFont("jLabel16.font")); // NOI18N
        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

        mat.setText(resourceMap.getString("mat.text")); // NOI18N
        mat.setName("mat"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(salaire, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(nbr_mission, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(text_direction, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(text_grade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(text_date_debut_contrat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(text_date_premier_contrat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(text_service, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(text_type_permis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(text_prenom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(text_nom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(text_experience, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(text_date_fin_contrat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(mat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(cin, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(text_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(text_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(text_type_permis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(text_experience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(text_date_premier_contrat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(text_date_debut_contrat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(text_date_fin_contrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(text_service, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(text_grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(text_direction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(nbr_mission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(salaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(518, 518, 518)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton7)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2)
                                    .addComponent(jButton5)
                                    .addComponent(jButton6)
                                    .addComponent(jButton3)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(mat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
    Acceil acc = new Acceil();
    acc.setVisible(true);
    setVisible(false);
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
    try{
    stmt=cnx.obtenircon().createStatement();


    ResultSet rslt=stmt.executeQuery("select * from chauffeur as CH where CH.num_chauffeur='"+Integer.parseInt(mat.getText())+"'");
    while(rslt.next()){
        text_nom.setText(rslt.getString("nom_chauffeur"));
        text_prenom.setText(rslt.getString("prenom_chauffeur"));
        text_experience.setText(rslt.getString("experience"));
        text_type_permis.setText(rslt.getString("type_permis"));
        text_date_premier_contrat.setText(rslt.getString("date_premier_contrat"));
        text_date_debut_contrat.setText(rslt.getString("date_debut_contrat"));
        text_date_fin_contrat.setText(rslt.getString("date_fin_contrat"));
        text_service.setText(rslt.getString("service"));
        text_grade.setText(rslt.getString("grade"));
        text_direction.setText(rslt.getString("direction"));
        nbr_mission.setText(rslt.getString("mission_realise"));
        salaire.setText(rslt.getString("salaire"));
        cin.setText(rslt.getString("cin"));
    }
    }catch(SQLException exp){
        JOptionPane.showMessageDialog(null, "erreur");
    }
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
DefaultTableModel table=(DefaultTableModel) tablechauffeur.getModel();
    
    try{
        
    stmt=   (Statement) cnx.obtenircon().createStatement();
    ResultSet rslt=stmt.executeQuery("select * from chauffeur");
    while(rslt.next()){
         
    table.addRow(new Object[] {rslt.getObject("num_chauffeur"),rslt.getObject("cin"),rslt.getObject("nom_chauffeur"),rslt.getObject("prenom_chauffeur"),rslt.getObject("type_permis"),rslt.getObject("experience"),rslt.getObject("date_premier_contrat"),rslt.getObject("date_debut_contrat"),rslt.getObject("date_fin_contrat"),rslt.getObject("service"),rslt.getObject("grade"), rslt.getObject("direction"),rslt.getObject("mission_realise"), rslt.getObject("salaire")});
        //i++;
    }
    
    
}                                        
catch(SQLException exp){
    JOptionPane.showMessageDialog(null,"erreur d'affichage");
}
}//GEN-LAST:event_jButton7ActionPerformed

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
MessageFormat header = new MessageFormat("Sotacib liste des véhicules");
MessageFormat footer = new MessageFormat("Page{0,Number, Integer}");
try{
    tablechauffeur.print(JTable.PrintMode.NORMAL, header, footer);
}catch(PrinterException e){
    System.err.format("cannot print", e.getMessage());
}
}//GEN-LAST:event_jButton8ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
    stmt=cnx.obtenircon().createStatement();
   int valcin = Integer.parseInt(cin.getText());
   String valnom = text_nom.getText();
   String valprenom = text_prenom.getText();
   String valpermis = text_type_permis.getText();
   String valpremiercont= text_date_premier_contrat.getText();
   String valdebutcont = text_date_debut_contrat.getText();
   String valfincont = text_date_fin_contrat.getText();
   String valservice = text_service.getText();
   String valdirection = text_grade.getText();
   int valexper = Integer.parseInt(text_experience.getText());
   int nbrmissions = Integer.parseInt(nbr_mission.getText());
   stmt.execute("update chauffeur set num_chauffeur='"+Integer.parseInt(mat.getText())+"', cin='"+valcin+"', nom_chauffeur='"+valnom+"', prenom_chauffeur='"+valprenom+"', date_premier_contrat='"+valpremiercont+"', date_debut_contrat='"+valdebutcont+"', date_fin_contrat='"+valfincont+"', experience='"+valexper+"', mission_realise='"+nbrmissions+"', type_permis='"+valpermis+"', service='"+valservice+"', grade='"+text_grade.getText()+"', direction='"+valdirection+"', salaire='"+Double.parseDouble(salaire.getText())+"' where num_chauffeur='"+Integer.parseInt(mat.getText())+"'");
   JOptionPane.showMessageDialog(null, "table modifié");
}
        catch(SQLException ex){
  JOptionPane.showMessageDialog(null, "erreur");  
}
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    String scin=cin.getText();
    int ncin=Integer.parseInt(scin);
    int res;
    res=JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment supprimer?");
    if(res==0){
    try {
            stmt=cnx.obtenircon().createStatement();
            stmt.executeUpdate("delete from chauffeur where cin="+ncin);
            JOptionPane.showMessageDialog(null, "supprimé"); 
            text_date_premier_contrat.setText("");
       text_date_debut_contrat.setText("");
       text_date_fin_contrat.setText("");
       text_experience.setText("");
       cin.setText("");
       text_nom.setText("");
       text_prenom.setText("");
       text_service.setText("");
       text_grade.setText("");
       text_type_permis.setText("");
       text_direction.setText("");
       nbr_mission.setText("");
       salaire.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(Supprimer_chauffeurs.class.getName()).log(Level.SEVERE, null, ex);
        }}
else{JOptionPane.showMessageDialog(null, "annulé");}
}//GEN-LAST:event_jButton5ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       text_date_premier_contrat.setText("");
       text_date_debut_contrat.setText("");
       text_date_fin_contrat.setText("");
       text_experience.setText("");
       cin.setText("");
       text_nom.setText("");
       text_prenom.setText("");
       text_service.setText("");
       text_grade.setText("");
       text_direction.setText("");
       text_type_permis.setText("");
       salaire.setText("");
       nbr_mission.setText("");
       mat.setText("");
}//GEN-LAST:event_jButton2ActionPerformed

private void tablechauffeurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablechauffeurMouseClicked
try{
    stmt=cnx.obtenircon().createStatement();
    
    int row=tablechauffeur.getSelectedRow();
    String table = (tablechauffeur.getModel().getValueAt(row,0).toString());
    ResultSet rs =stmt.executeQuery("select * from chauffeur where num_chauffeur="+table);
    if(rs.next()){
        String add14=rs.getString("num_chauffeur");
        mat.setText(add14);
        String add1=rs.getString("cin");
        cin.setText(add1);
        String add2=rs.getString("nom_chauffeur");
        text_nom.setText(add2);
        String add3=rs.getString("prenom_chauffeur");
        text_prenom.setText(add3);
        String add4=rs.getString("date_premier_contrat");
        text_date_premier_contrat.setText(add4);
        String add5=rs.getString("date_debut_contrat");
        text_date_debut_contrat.setText(add5);
        String add6=rs.getString("date_fin_contrat");
        text_date_fin_contrat.setText(add6);
        String add7=rs.getString("experience");
        text_experience.setText(add7);
        String add8=rs.getString("type_permis");
        text_type_permis.setText(add8);
        String add9=rs.getString("service");
        text_service.setText(add9);
        String add10=rs.getString("direction");
        text_direction.setText(add10);
        String add11=rs.getString("grade");
        text_grade.setText(add11);
        String add12=rs.getString("mission_realise");
        nbr_mission.setText(add12);
        String add13=rs.getString("salaire");
        salaire.setText(add13);
        
    }
}catch(Exception e){
    
}
}//GEN-LAST:event_tablechauffeurMouseClicked

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
nouv_contrat_chauffeur ncc = new nouv_contrat_chauffeur();
ncc.setVisible(true);
this.setVisible(false);
}//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supprimer_chauffeurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supprimer_chauffeurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supprimer_chauffeurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supprimer_chauffeurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Supprimer_chauffeurs().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mat;
    private javax.swing.JTextField nbr_mission;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTextField salaire;
    private javax.swing.JTable tablechauffeur;
    private javax.swing.JTextField text_date_debut_contrat;
    private javax.swing.JTextField text_date_fin_contrat;
    private javax.swing.JTextField text_date_premier_contrat;
    private javax.swing.JTextField text_direction;
    private javax.swing.JTextField text_experience;
    private javax.swing.JTextField text_grade;
    private javax.swing.JTextField text_nom;
    private javax.swing.JTextField text_prenom;
    private javax.swing.JTextField text_service;
    private javax.swing.JTextField text_type_permis;
    // End of variables declaration//GEN-END:variables
}
