/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * user_account.java
 *
 * Created on 22 mai 2014, 23:13:28
 */
package pfe;

import java.sql.*;
import javax.swing.JOptionPane;
public class user_account extends javax.swing.JFrame {

    Connexion cnx = new Connexion();
    Statement stmt;
    public user_account() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        fct = new javax.swing.JComboBox();
        pass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pfe.PFEApp.class).getContext().getResourceMap(user_account.class);
        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setIcon(resourceMap.getIcon("jLabel2.icon")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        mat.setText(resourceMap.getString("mat.text")); // NOI18N
        mat.setName("mat"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        fct.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sélectinner la fonction","Administrateur", "Administrateur garage", "Agent"}));
        fct.setName("fct"); // NOI18N

        pass.setText(resourceMap.getString("pass.text")); // NOI18N
        pass.setName("pass"); // NOI18N
        pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passMouseClicked(evt);
            }
        });
        pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                    .addComponent(jButton2)
                                    .addGap(27, 27, 27)
                                    .addComponent(jButton3))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(36, 36, 36)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                        .addComponent(mat, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                        .addComponent(fct, 0, 157, Short.MAX_VALUE)))))))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(mat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(fct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3)
                            .addComponent(jButton2))))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int index = fct.getSelectedIndex();
    switch(index){
        case 0: {
            JOptionPane.showMessageDialog(null,"Veuillez sélectionner la fonction"); 
        }
        case 1:{
          checkadmin(); 
    }break;
        case 2:{    
           checkadming(); 
        }break;
        case 3:{
        try{
        stmt=cnx.obtenircon().createStatement();
    stmt.executeUpdate("insert into users (matricule, password, fonction) values ('"+Integer.parseInt(mat.getText())+"','"+pass.getText()+"','"+fct.getSelectedItem().toString()+"')");
    JOptionPane.showMessageDialog(null,"Votre compte a été creé");
        }catch(SQLException e){
        }
        }break;
    }
    /*String passw="";
    if(fct.getSelectedIndex()==0){
        JOptionPane.showMessageDialog(null,"Veuillez sélectionner la fonction");
        
    }else{
        if((fct.getSelectedIndex()==1)||(fct.getSelectedIndex()==2)){
         try{
            stmt=cnx.obtenircon().createStatement();
            ResultSet rst = stmt.executeQuery("select password from users where fonction = 'Administrateur' or fonction = 'Administrateur garage'");
            while(rst.next()){
                 passw = rst.getString("password");
            }
            if(     !"".equals(passw)){JOptionPane.showMessageDialog(null,"un compte administrateur existe déja");
            jButton1.setEnabled(false);
            }
        stmt.close();
        }catch(SQLException e){
    JOptionPane.showMessageDialog(null, e);
}
        }
        else{
        try{
        stmt=cnx.obtenircon().createStatement();
    stmt.executeUpdate("insert into users (matricule, password, fonction) values ('"+Integer.parseInt(mat.getText())+"','"+pass.getText()+"','"+fct.getSelectedItem().toString()+"')");
    JOptionPane.showMessageDialog(null,"Votre compte a été creé");
        }catch(SQLException e){
        }
        }
    
    }*/
}//GEN-LAST:event_jButton1ActionPerformed

private void passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMouseClicked
if (    "".equals(mat.getText())){JOptionPane.showMessageDialog(null,"champ matricule ne doit pas etre vide");
jButton1.setEnabled(false);
}else{jButton1.setEnabled(true);
try{
    stmt=cnx.obtenircon().createStatement();
    ResultSet rst=stmt.executeQuery("select matricule from users");
    while(rst.next()){
        if(rst.getInt("matricule")==Integer.parseInt(mat.getText())){
            JOptionPane.showMessageDialog(null,"matricule existe");
            jButton1.setEnabled(false);
        }
    }
}catch(SQLException e){
    JOptionPane.showMessageDialog(null,e);
}}
}//GEN-LAST:event_passMouseClicked

private void passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusLost
if(     "".equals(pass.getText())){
    JOptionPane.showMessageDialog(null,"champ mot de passe ne doit pas etre vide");
    jButton1.setEnabled(false);
}else{
    jButton1.setEnabled(true);
}
}//GEN-LAST:event_passFocusLost

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Authentication aut = new Authentication (); aut.setVisible(true);this.setVisible(false);
}//GEN-LAST:event_jButton3ActionPerformed
private void createaccount(){
try{
        stmt=cnx.obtenircon().createStatement();
    stmt.executeUpdate("insert into users (matricule, password, fonction) values ('"+Integer.parseInt(mat.getText())+"','"+pass.getText()+"','"+fct.getSelectedItem().toString()+"')");
    JOptionPane.showMessageDialog(null,"Votre compte a été creé");
        }catch(SQLException e){
        }
        
}
private void checkadmin(){
String passw="";
    try{
            stmt=cnx.obtenircon().createStatement();
            ResultSet rst = stmt.executeQuery("select password from users where fonction = 'Administrateur'");
            while(rst.next()){
                passw = rst.getString("password");
            }
            if(     !"".equals(passw)){JOptionPane.showMessageDialog(null,"un compte administrateur existe déja");
            jButton1.setEnabled(false);
            }else{
            jButton1.setEnabled(true);
            createaccount();
            } 
        }catch(SQLException e){}
}
private void checkadming(){
    String passw="";
    try{
    stmt=cnx.obtenircon().createStatement();
            ResultSet rst = stmt.executeQuery("select password from users where fonction = 'Administrateur garage'");
            while(rst.next()){
                passw = rst.getString("password");
            }
            if(     !"".equals(passw)){JOptionPane.showMessageDialog(null,"un compte administrateur existe déja");
            jButton1.setEnabled(false);
            }else{
            jButton1.setEnabled(true);
            createaccount();
            }  
    }catch(SQLException e){
    }
     
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new user_account().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox fct;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mat;
    private javax.swing.JPasswordField pass;
    // End of variables declaration//GEN-END:variables
}
